using System.ComponentModel.DataAnnotations;

namespace Hackathon.Models
{
    public class SITE_SCORE_PARAM
    {
        [Key]
        public int SITEID_PK { get; set; }
        public int? TOTAL_OBSERVATION_PER_SITE { get; set; }
        public int? total_Other_Electrical_OBS { get; set; }
        public int? total_Non_Work_Related_Medical_Issue_OBS { get; set; }
        public int? total_Pest_Exposure_OBS { get; set; }
        public int? total_Domestic_Animals_OBS { get; set; }
        public int? total_BBP_OBS { get; set; }
        public int? total_Client_Action_Required_OBS { get; set; }
        public int? total_Out_of_Scope_OBS { get; set; }
        public int? total_Lone_Workers_OBS { get; set; }
        public int? total_BBP_Bloodborne_pathegens_OBS { get; set; }
        public int? total_Harrasment_Violence_OBS { get; set; }
        public int? total_SIF_OBS { get; set; }
        public int? total_Pest_Control_OBS { get; set; }
        public int? total_Behavior_Attitude_OBS { get; set; }
        public int? total_Job_Hazard_Assessment_OBS { get; set; }
        public int? total_Bad_words_OBS { get; set; }
        public int? total_Machine_Guarding_OBS { get; set; }
        public int? total_Lone_Working_OBS { get; set; }
        public int? total_Hot_Work_OBS { get; set; }
        public int? total_Arc_Flash_OBS { get; set; }
        public int? total_Hazardous_Material_Waste_OBS { get; set; }
        public int? total_Emergency_Planning_OBS { get; set; }
        public int? total_Sustainability_OBS { get; set; }
        public int? total_PIT_OBS { get; set; }
        public int? total_Work_Related_Medical_Issue_OBS { get; set; }
        public int? total_Environment_OBS { get; set; }
        public int? total_Ergonomics_OBS { get; set; }
        public int? total_Change_Management_OBS { get; set; }
        public int? total_Confined_Space_OBS { get; set; }
        public int? total_SprainsStrains_OBS { get; set; }
        public int? total_Legal_Regulatory_OBS { get; set; }
        public int? total_Landscaping_OBS { get; set; }
        public int? total_Training_OBS { get; set; }
        public int? total_Driving_Behavior_OBS { get; set; }
        public int? total_Polution_OBS { get; set; }
        public int? total_Governance_Policy_Procedures_OBS { get; set; }
        public int? total_PPE_OBS { get; set; }
        public int? total_AerialWork_platform_OBS { get; set; }
        public int? total_Machinery_OBS { get; set; }
        public int? total_Animals_and_Pest_Control_OBS { get; set; }
        public int? total_Debris_Trash_OBS { get; set; }
        public int? total_Indoor_Air_Quality_OBS { get; set; }
        public int? total_Laceration_OBS { get; set; }
        public int? total_Health_Wellbeing_OBS { get; set; }
        public int? total_Tools_OBS { get; set; }
        public int? total_Manual_Handling_OBS { get; set; }
        public int? total_Human_Performance_OBS { get; set; }
        public int? total_Fuel_Management_OBS { get; set; }
        public int? total_Medical_OBS { get; set; }
        public int? total_Industrial_Hygiene_OBS { get; set; }
        public int? total_Hazardous_substances_OBS { get; set; }
        public int? total_Water_OBS { get; set; }
        public int? total_Risk_Assessment_OBS { get; set; }
        public int? total_Leadership_Commitment_OBS { get; set; }
        public int? total_Waste_Management_OBS { get; set; }
        public int? total_Arc_Flash_Other_Electrical_ElectricalArc_Flash_OBS { get; set; }
        public int? total_Emergency_Management_OBS { get; set; }
        public int? total_Hazardous_Energy_Control_OBS { get; set; }
        public int? total_FireLife_Safety_OBS { get; set; }
        public int? total_PPE_personal_protective_equipment_OBS { get; set; }
        public int? total_Emergency_Response_OBS { get; set; }
        public int? total_Fleet_Transportation_OBS { get; set; }
        public int? total_Hand_Portable_Tools_OBS { get; set; }
        public int? total_Workplace_Design_OBS { get; set; }
        public int? total_Assurance_Audit_OBS { get; set; }
        public int? total_Hazardous_Energy_OBS { get; set; }
        public int? total_Working_at_Heights_OBS { get; set; }
        public int? total_Fire_Safety_OBS { get; set; }
        public int? total_none_OBS { get; set; }
        public int? total_Housekeeping_OBS { get; set; }
        public int? total_Equipment_Maintenance_OBS { get; set; }
        public int? total_Walking_Working_Surfaces_OBS { get; set; }
        public int? total_HIGH_SEV_OBS { get; set; }
        public int? total_MEDIUM_SEV_OBS { get; set; }
        public int? total_LOW_SEV_OBS { get; set; }
        public int? total_NONE_SEV_OBS { get; set; }
        public int? TOTAL_GOOD_CATCH_OBS { get; set; }
        public int? TOTAL_UNSAFE_CONDITION_OBS { get; set; }
        public int? TOTAL_UNSAFE_ACT_OBS { get; set; }
        public int? TOTAL_NOT_CATE_OBS { get; set; }
        public int? total_OPEN_OBS { get; set; }
        public int? total_CLOSE_OBS { get; set; }
        public int? total_AWAITING_REVIEW_OBS { get; set; }
        public int? total_INREVIEW_OBS { get; set; }
        public int? total_RESOLVED_OBS { get; set; }
        public int? TOTAL_INCIDENT_PER_SITE { get; set; }
        public int? total_Environmental_Incident { get; set; }
        public int? total_Fleet_Incident { get; set; }
        public int? total_Inj_illness_Incident { get; set; }
        public int? total_nonInj_Incident { get; set; }
        public int? total_PropertyDamage_incident { get; set; }
        public int? total_QualityEvent_Incident { get; set; }
        public int? total_Regulatory_Incident { get; set; }
        public int? total_nonRecordableNonReportable_Incident { get; set; }
        public int? total_Recordable_Incident { get; set; }
        public int? total_RecordableReportable_Incident { get; set; }
        public int? total_Reportable_Incident { get; set; }
        public int? total_claims_per_site_Incident { get; set; }
        public int? days_since_last_end_of_life_event { get; set; }
        public int? total_cancelled_INC { get; set; }
        public int? total_CLOSE_INC { get; set; }
        public int? total_COMPLETED_INC { get; set; }
        public int? total_OPEN_INC { get; set; }
        public int? total_away_days { get; set; }
        public int? total_restricted_days { get; set; }
        public int? total_OPEN_AUD { get; set; }
        public int? total_CLOSE_AUD { get; set; }
        public int? total_CANCELLED_AUD { get; set; }
        public int? total_INREVIEW_AUD { get; set; }
        public int? total_RESOLVED_AUD { get; set; }
        public int? total_INPROGRESS_AUD { get; set; }
        public int? TOTAL_AUDITS_PER_SITE { get; set; }
        public int? total_undesired_responses { get; set; }
        public int? TOTAL_ACTIONS_PER_SITE { get; set; }
        public int? total_OPEN_ACT { get; set; }
        public int? total_CLOSE_ACT { get; set; }
        public int? total_CANCELLED_ACT { get; set; }
        public int? total_COMPLETED_ACT { get; set; }
        public int? total_ONHOLD_ACT { get; set; }
        public int? total_INPROGRESS_ACT { get; set; }
        public int? total_NotStarted_ACT { get; set; }
        public int? total_Resolved_ACT { get; set; }
        public int? TOTAL_INVESTIGATIONS_PER_SITE { get; set; }
        public int? total_OPEN_INV { get; set; }
        public int? total_CLOSE_INV { get; set; }
        public int? total_CANCELLED_INV { get; set; }
        public int? total_COMPLETED_INV { get; set; }
        public int? total_INPROGRESS_INV { get; set; }
        public string? Risk_Category { get; set; }
        public string? Manual_category { get; set; }
        public int SITE_PK { get; set; }
    }
}
